# Generated by Django 4.2 on 2025-08-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='TheSportsDB Player ID', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Player full name', max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Player short name', max_length=100)),
                ('nationality', models.CharField(blank=True, help_text='Player nationality', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Player birth date', null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Player current age', null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('position', models.CharField(blank=True, help_text='Player position', max_length=50)),
                ('position_category', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward'), ('SUB', 'Substitute'), ('COACH', 'Coach/Manager')], help_text='Position category', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Injured', 'Injured'), ('Loan', 'On Loan'), ('Unknown', 'Unknown')], default='Active', max_length=20)),
                ('photo_url', models.URLField(blank=True, help_text='Player photo thumbnail')),
                ('cutout_url', models.URLField(blank=True, help_text='Player cutout image')),
                ('description', models.TextField(blank=True, help_text='Player description/biography')),
                ('height', models.CharField(blank=True, help_text='Player height', max_length=20)),
                ('weight', models.CharField(blank=True, help_text='Player weight', max_length=20)),
                ('wage', models.CharField(blank=True, help_text='Player wage/salary', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last API sync timestamp', null=True)),
                ('team', models.ForeignKey(blank=True, help_text='Current team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.team')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(help_text='Date of transfer')),
                ('transfer_type', models.CharField(choices=[('Permanent', 'Permanent Transfer'), ('Loan', 'Loan'), ('Free', 'Free Transfer'), ('Contract', 'Contract Renewal'), ('Release', 'Contract Release')], default='Permanent', max_length=20)),
                ('transfer_fee', models.CharField(blank=True, help_text='Transfer fee amount', max_length=50)),
                ('currency', models.CharField(blank=True, help_text='Currency of transfer fee', max_length=10)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Transfer confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_team', models.ForeignKey(blank=True, help_text='Team player transferred from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='core.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.player')),
                ('to_team', models.ForeignKey(blank=True, help_text='Team player transferred to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='core.team')),
            ],
            options={
                'db_table': 'player_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearances', models.PositiveIntegerField(default=0, help_text='Total appearances')),
                ('minutes_played', models.PositiveIntegerField(default=0, help_text='Total minutes played')),
                ('starts', models.PositiveIntegerField(default=0, help_text='Games started')),
                ('substitutions_in', models.PositiveIntegerField(default=0, help_text='Times substituted in')),
                ('substitutions_out', models.PositiveIntegerField(default=0, help_text='Times substituted out')),
                ('goals', models.PositiveIntegerField(default=0, help_text='Goals scored')),
                ('assists', models.PositiveIntegerField(default=0, help_text='Assists made')),
                ('penalty_goals', models.PositiveIntegerField(default=0, help_text='Penalty goals')),
                ('freekick_goals', models.PositiveIntegerField(default=0, help_text='Free kick goals')),
                ('yellow_cards', models.PositiveIntegerField(default=0, help_text='Yellow cards received')),
                ('red_cards', models.PositiveIntegerField(default=0, help_text='Red cards received')),
                ('clean_sheets', models.PositiveIntegerField(default=0, help_text='Clean sheets (GK)')),
                ('saves', models.PositiveIntegerField(default=0, help_text='Saves made (GK)')),
                ('goals_conceded', models.PositiveIntegerField(default=0, help_text='Goals conceded (GK)')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Average performance rating', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, help_text='Competition for these statistics', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.player')),
                ('season', models.ForeignKey(help_text='Season for these statistics', on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
            options={
                'db_table': 'player_statistics',
                'ordering': ['-season', 'player'],
            },
        ),
        migrations.AddIndex(
            model_name='playertransfer',
            index=models.Index(fields=['player', 'transfer_date'], name='player_tran_player__c3102f_idx'),
        ),
        migrations.AddIndex(
            model_name='playertransfer',
            index=models.Index(fields=['from_team'], name='player_tran_from_te_d86e20_idx'),
        ),
        migrations.AddIndex(
            model_name='playertransfer',
            index=models.Index(fields=['to_team'], name='player_tran_to_team_ba0f10_idx'),
        ),
        migrations.AddIndex(
            model_name='playertransfer',
            index=models.Index(fields=['transfer_type'], name='player_tran_transfe_8069d4_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatistics',
            index=models.Index(fields=['player', 'season'], name='player_stat_player__7658f5_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatistics',
            index=models.Index(fields=['season', 'competition'], name='player_stat_season__b0c938_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatistics',
            index=models.Index(fields=['goals'], name='player_stat_goals_e6a581_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatistics',
            index=models.Index(fields=['assists'], name='player_stat_assists_e6e31b_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatistics',
            index=models.Index(fields=['appearances'], name='player_stat_appeara_d89117_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstatistics',
            unique_together={('player', 'season', 'competition')},
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['external_id'], name='players_externa_7c74e2_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team'], name='players_team_id_483bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['nationality'], name='players_nationa_28e48b_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position_category'], name='players_positio_9c4cef_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['status'], name='players_status_e7b22b_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='players_name_0574eb_idx'),
        ),
    ]
