# Generated by Django 4.2 on 2025-09-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_playertransfer_playerstatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRE_MATCH', 'Pre-Match'), ('KICK_OFF', 'Kick Off'), ('FIRST_HALF', 'First Half'), ('HALF_TIME', 'Half Time'), ('SECOND_HALF', 'Second Half'), ('EXTRA_TIME_FIRST', 'Extra Time - First Half'), ('EXTRA_TIME_BREAK', 'Extra Time - Break'), ('EXTRA_TIME_SECOND', 'Extra Time - Second Half'), ('PENALTY_SHOOTOUT', 'Penalty Shootout'), ('FULL_TIME', 'Full Time'), ('SUSPENDED', 'Suspended'), ('ABANDONED', 'Abandoned')], default='PRE_MATCH', max_length=20)),
                ('minute', models.IntegerField(default=0)),
                ('added_time', models.IntegerField(default=0)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('home_possession', models.FloatField(default=0.0)),
                ('away_possession', models.FloatField(default=0.0)),
                ('home_shots', models.IntegerField(default=0)),
                ('away_shots', models.IntegerField(default=0)),
                ('home_shots_on_target', models.IntegerField(default=0)),
                ('away_shots_on_target', models.IntegerField(default=0)),
                ('home_corners', models.IntegerField(default=0)),
                ('away_corners', models.IntegerField(default=0)),
                ('home_fouls', models.IntegerField(default=0)),
                ('away_fouls', models.IntegerField(default=0)),
                ('home_yellow_cards', models.IntegerField(default=0)),
                ('away_yellow_cards', models.IntegerField(default=0)),
                ('home_red_cards', models.IntegerField(default=0)),
                ('away_red_cards', models.IntegerField(default=0)),
                ('home_offsides', models.IntegerField(default=0)),
                ('away_offsides', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('temperature', models.CharField(blank=True, max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_data', to='core.match')),
            ],
            options={
                'db_table': 'live_matches',
            },
        ),
        migrations.CreateModel(
            name='MatchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('MATCH_START', 'Match Started'), ('GOAL', 'Goal Scored'), ('RED_CARD', 'Red Card'), ('PENALTY', 'Penalty'), ('HALF_TIME', 'Half Time'), ('FULL_TIME', 'Full Time'), ('ODDS_MOVEMENT', 'Significant Odds Movement'), ('VALUE_BET', 'Value Bet Opportunity'), ('SCORE_PREDICTION', 'Score Prediction Update'), ('COMEBACK_ALERT', 'Comeback Possibility'), ('UPSET_ALERT', 'Upset in Progress')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('target_subscription_levels', models.JSONField(default=list)),
                ('sent_count', models.IntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('send_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.match')),
                ('target_teams', models.ManyToManyField(blank=True, to='core.team')),
            ],
            options={
                'db_table': 'match_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveOddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('home_odds', models.FloatField()),
                ('draw_odds', models.FloatField()),
                ('away_odds', models.FloatField()),
                ('over_0_5_odds', models.FloatField(blank=True, null=True)),
                ('under_0_5_odds', models.FloatField(blank=True, null=True)),
                ('over_1_5_odds', models.FloatField(blank=True, null=True)),
                ('under_1_5_odds', models.FloatField(blank=True, null=True)),
                ('over_2_5_odds', models.FloatField(blank=True, null=True)),
                ('under_2_5_odds', models.FloatField(blank=True, null=True)),
                ('over_3_5_odds', models.FloatField(blank=True, null=True)),
                ('under_3_5_odds', models.FloatField(blank=True, null=True)),
                ('both_teams_score_yes', models.FloatField(blank=True, null=True)),
                ('both_teams_score_no', models.FloatField(blank=True, null=True)),
                ('home_next_goal_odds', models.FloatField(blank=True, null=True)),
                ('away_next_goal_odds', models.FloatField(blank=True, null=True)),
                ('no_more_goals_odds', models.FloatField(blank=True, null=True)),
                ('value_percentage', models.FloatField(default=0.0)),
                ('is_value_bet', models.BooleanField(default=False)),
                ('bookmaker_source', models.CharField(default='Multiple', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('live_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='core.livematch')),
            ],
            options={
                'db_table': 'live_odds_snapshots',
                'ordering': ['minute', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LiveMatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('OWN_GOAL', 'Own Goal'), ('PENALTY_GOAL', 'Penalty Goal'), ('YELLOW_CARD', 'Yellow Card'), ('RED_CARD', 'Red Card'), ('SUBSTITUTION', 'Substitution'), ('VAR_REVIEW', 'VAR Review'), ('VAR_DECISION', 'VAR Decision'), ('INJURY', 'Injury'), ('CORNER', 'Corner'), ('FREE_KICK', 'Free Kick'), ('PENALTY_AWARDED', 'Penalty Awarded'), ('PENALTY_MISSED', 'Penalty Missed'), ('OFFSIDE', 'Offside'), ('KICK_OFF', 'Kick Off'), ('HALF_TIME', 'Half Time'), ('FULL_TIME', 'Full Time')], max_length=20)),
                ('minute', models.IntegerField()),
                ('added_time', models.IntegerField(default=0)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('x_coordinate', models.FloatField(blank=True, null=True)),
                ('y_coordinate', models.FloatField(blank=True, null=True)),
                ('external_event_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assist_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='core.player')),
                ('live_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.livematch')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player')),
                ('substitute_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to='core.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
            options={
                'db_table': 'live_match_events',
                'ordering': ['minute', 'added_time', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='matchalert',
            index=models.Index(fields=['match', 'alert_type'], name='match_alert_match_i_64fe13_idx'),
        ),
        migrations.AddIndex(
            model_name='matchalert',
            index=models.Index(fields=['priority'], name='match_alert_priorit_477ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='matchalert',
            index=models.Index(fields=['is_sent'], name='match_alert_is_sent_07f7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='matchalert',
            index=models.Index(fields=['created_at'], name='match_alert_created_1cb966_idx'),
        ),
        migrations.AddIndex(
            model_name='matchalert',
            index=models.Index(fields=['send_after'], name='match_alert_send_af_3b1627_idx'),
        ),
        migrations.AddIndex(
            model_name='liveoddssnapshot',
            index=models.Index(fields=['live_match', 'minute'], name='live_odds_s_live_ma_a7b6db_idx'),
        ),
        migrations.AddIndex(
            model_name='liveoddssnapshot',
            index=models.Index(fields=['is_value_bet'], name='live_odds_s_is_valu_09bf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='liveoddssnapshot',
            index=models.Index(fields=['timestamp'], name='live_odds_s_timesta_e821f3_idx'),
        ),
        migrations.AddIndex(
            model_name='livematchevent',
            index=models.Index(fields=['live_match', 'minute'], name='live_match__live_ma_508554_idx'),
        ),
        migrations.AddIndex(
            model_name='livematchevent',
            index=models.Index(fields=['event_type'], name='live_match__event_t_f19b37_idx'),
        ),
        migrations.AddIndex(
            model_name='livematchevent',
            index=models.Index(fields=['player'], name='live_match__player__ba1596_idx'),
        ),
        migrations.AddIndex(
            model_name='livematchevent',
            index=models.Index(fields=['team'], name='live_match__team_id_a044b3_idx'),
        ),
        migrations.AddIndex(
            model_name='livematchevent',
            index=models.Index(fields=['created_at'], name='live_match__created_d77165_idx'),
        ),
        migrations.AddIndex(
            model_name='livematch',
            index=models.Index(fields=['status'], name='live_matche_status_9dea55_idx'),
        ),
        migrations.AddIndex(
            model_name='livematch',
            index=models.Index(fields=['is_active'], name='live_matche_is_acti_27c8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='livematch',
            index=models.Index(fields=['last_update'], name='live_matche_last_up_f1852a_idx'),
        ),
    ]
