# Generated by Django 4.2 on 2025-09-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_player_playertransfer_playerstatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmakerProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_endpoint', models.URLField()),
                ('api_key_required', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('reliability_score', models.FloatField(default=0.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bookmaker Provider',
                'verbose_name_plural': 'Bookmaker Providers',
            },
        ),
        migrations.CreateModel(
            name='MatchOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win_odds', models.FloatField()),
                ('draw_odds', models.FloatField()),
                ('away_win_odds', models.FloatField()),
                ('total_goals_over_2_5', models.FloatField(blank=True, null=True)),
                ('total_goals_under_2_5', models.FloatField(blank=True, null=True)),
                ('both_teams_score_yes', models.FloatField(blank=True, null=True)),
                ('both_teams_score_no', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting_odds.bookmakerprovider')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='core.match')),
            ],
            options={
                'verbose_name': 'Match Odds',
                'verbose_name_plural': 'Match Odds',
                'unique_together': {('match', 'bookmaker')},
            },
        ),
        migrations.CreateModel(
            name='OddsMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win'), ('over_2_5', 'Over 2.5 Goals'), ('under_2_5', 'Under 2.5 Goals'), ('btts_yes', 'Both Teams Score Yes'), ('btts_no', 'Both Teams Score No')], max_length=50)),
                ('old_odds', models.FloatField()),
                ('new_odds', models.FloatField()),
                ('movement_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match_odds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='betting_odds.matchodds')),
            ],
            options={
                'verbose_name': 'Odds Movement',
                'verbose_name_plural': 'Odds Movements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OddsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_home_odds', models.FloatField()),
                ('average_draw_odds', models.FloatField()),
                ('average_away_odds', models.FloatField()),
                ('best_home_odds', models.FloatField(blank=True, null=True)),
                ('best_draw_odds', models.FloatField(blank=True, null=True)),
                ('best_away_odds', models.FloatField(blank=True, null=True)),
                ('value_bet_detected', models.BooleanField(default=False)),
                ('value_bet_market', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odds_analysis', to='core.match')),
            ],
            options={
                'verbose_name': 'Odds Analysis',
                'verbose_name_plural': 'Odds Analyses',
            },
        ),
        migrations.CreateModel(
            name='MarketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('odds_drop', 'Significant Odds Drop'), ('odds_rise', 'Significant Odds Rise'), ('value_bet', 'Value Bet Detected'), ('arbitrage', 'Arbitrage Opportunity'), ('steam_move', 'Steam Movement')], max_length=50)),
                ('market_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('old_odds', models.FloatField(blank=True, null=True)),
                ('new_odds', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_alerts', to='core.match')),
            ],
            options={
                'verbose_name': 'Market Alert',
                'verbose_name_plural': 'Market Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
