# Generated by Django 4.2 on 2025-08-28 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('question', models.TextField(verbose_name='Pergunta')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('closed', 'Fechada'), ('archived', 'Arquivada')], default='draft', max_length=20, verbose_name='Status')),
                ('featured_image', models.URLField(blank=True, verbose_name='Imagem Destacada')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='Múltipla Escolha')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Votação Anônima')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('total_votes', models.PositiveIntegerField(default=0, verbose_name='Total de Votos')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Texto da Opção')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.URLField(blank=True, verbose_name='Imagem')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Votos')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentagem')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll', verbose_name='Enquete')),
            ],
            options={
                'verbose_name': 'Opção da Enquete',
                'verbose_name_plural': 'Opções das Enquetes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_votes', to='polls.polloption', verbose_name='Opção')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='polls.poll', verbose_name='Enquete')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Curtidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='polls.pollcomment', verbose_name='Comentário Pai')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polls.poll', verbose_name='Enquete')),
            ],
            options={
                'verbose_name': 'Comentário da Enquete',
                'verbose_name_plural': 'Comentários das Enquetes',
                'ordering': ['-created_at'],
            },
        ),
    ]
