# Generated by Django 4.2 on 2025-09-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('extracted_text', models.CharField(max_length=200)),
                ('canonical_value', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField()),
                ('extraction_method', models.CharField(choices=[('regex', 'Regular Expression'), ('database', 'Database Match'), ('nlp', 'NLP Model'), ('manual', 'Manual Rule')], default='nlp', max_length=20)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nlp_entity_recognition_logs',
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('team', 'Team'), ('player', 'Player'), ('competition', 'Competition'), ('date', 'Date'), ('number', 'Number'), ('location', 'Location'), ('season', 'Season'), ('match_status', 'Match Status')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('pattern_regex', models.TextField(blank=True, help_text='Optional regex pattern for entity recognition')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nlp_entity_types',
            },
        ),
        migrations.CreateModel(
            name='EntityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('canonical_value', models.CharField(help_text='Standardized form of the value', max_length=200)),
                ('synonyms', models.JSONField(default=list, help_text='List of synonyms for this entity')),
                ('confidence_score', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nlp_entity_values',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('team_stats', 'Team Statistics'), ('player_stats', 'Player Statistics'), ('match_info', 'Match Information'), ('standings', 'League Standings'), ('subscription', 'Subscription Related'), ('help', 'Help/General'), ('betting_odds', 'Betting Odds'), ('predictions', 'Match Predictions'), ('news', 'Football News'), ('schedule', 'Match Schedule')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nlp_intents',
            },
        ),
        migrations.CreateModel(
            name='IntentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField(help_text='Pattern for matching user queries')),
                ('pattern_type', models.CharField(choices=[('regex', 'Regular Expression'), ('keyword', 'Keywords'), ('phrase', 'Exact Phrase'), ('semantic', 'Semantic Similarity')], default='keyword', max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='Pattern weight for scoring')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nlp_intent_patterns',
            },
        ),
        migrations.CreateModel(
            name='TrainingPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('language', models.CharField(default='pt', max_length=5)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nlp_training_phrases',
            },
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('normalized_query', models.TextField(blank=True)),
                ('detected_intent', models.CharField(blank=True, max_length=50)),
                ('intent_confidence', models.FloatField(blank=True, null=True)),
                ('detected_entities', models.JSONField(default=dict, help_text='Extracted entities with confidence scores')),
                ('response_generated', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('whatsapp_user_phone', models.CharField(blank=True, max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='pt', max_length=5)),
            ],
            options={
                'db_table': 'nlp_user_queries',
            },
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['timestamp'], name='nlp_user_qu_timesta_edbea9_idx'),
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['detected_intent'], name='nlp_user_qu_detecte_901033_idx'),
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['whatsapp_user_phone'], name='nlp_user_qu_whatsap_679a47_idx'),
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['was_successful'], name='nlp_user_qu_was_suc_24bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['language'], name='nlp_user_qu_languag_8fd8e9_idx'),
        ),
        migrations.AddField(
            model_name='trainingphrase',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_phrases', to='nlp_engine.intent'),
        ),
        migrations.AddField(
            model_name='intentpattern',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='nlp_engine.intent'),
        ),
        migrations.AddIndex(
            model_name='intent',
            index=models.Index(fields=['name'], name='nlp_intents_name_ef6ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='intent',
            index=models.Index(fields=['is_active'], name='nlp_intents_is_acti_001c88_idx'),
        ),
        migrations.AddField(
            model_name='entityvalue',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='nlp_engine.entitytype'),
        ),
        migrations.AddIndex(
            model_name='entitytype',
            index=models.Index(fields=['name'], name='nlp_entity__name_4b7f08_idx'),
        ),
        migrations.AddIndex(
            model_name='entitytype',
            index=models.Index(fields=['is_active'], name='nlp_entity__is_acti_d86f07_idx'),
        ),
        migrations.AddField(
            model_name='entityrecognitionlog',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_logs', to='nlp_engine.userquery'),
        ),
        migrations.AddIndex(
            model_name='trainingphrase',
            index=models.Index(fields=['intent'], name='nlp_trainin_intent__95581c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingphrase',
            index=models.Index(fields=['language'], name='nlp_trainin_languag_6b8755_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingphrase',
            index=models.Index(fields=['is_active'], name='nlp_trainin_is_acti_708724_idx'),
        ),
        migrations.AddIndex(
            model_name='intentpattern',
            index=models.Index(fields=['intent'], name='nlp_intent__intent__d39e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='intentpattern',
            index=models.Index(fields=['pattern_type'], name='nlp_intent__pattern_40f915_idx'),
        ),
        migrations.AddIndex(
            model_name='intentpattern',
            index=models.Index(fields=['is_active'], name='nlp_intent__is_acti_209106_idx'),
        ),
        migrations.AddIndex(
            model_name='entityvalue',
            index=models.Index(fields=['entity_type'], name='nlp_entity__entity__df2331_idx'),
        ),
        migrations.AddIndex(
            model_name='entityvalue',
            index=models.Index(fields=['canonical_value'], name='nlp_entity__canonic_698dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='entityvalue',
            index=models.Index(fields=['is_active'], name='nlp_entity__is_acti_b7a28c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entityvalue',
            unique_together={('entity_type', 'canonical_value')},
        ),
        migrations.AddIndex(
            model_name='entityrecognitionlog',
            index=models.Index(fields=['query'], name='nlp_entity__query_i_4ba8db_idx'),
        ),
        migrations.AddIndex(
            model_name='entityrecognitionlog',
            index=models.Index(fields=['entity_type'], name='nlp_entity__entity__5ad8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='entityrecognitionlog',
            index=models.Index(fields=['confidence_score'], name='nlp_entity__confide_6c3938_idx'),
        ),
        migrations.AddIndex(
            model_name='entityrecognitionlog',
            index=models.Index(fields=['extraction_method'], name='nlp_entity__extract_b628f4_idx'),
        ),
    ]
