# Generated by Django 4.2 on 2025-09-01 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_premium', models.BooleanField(default=False)),
                ('subscription_plan', models.CharField(default='free', max_length=20)),
                ('daily_queries_count', models.IntegerField(default=0)),
                ('last_query_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('context_data', models.JSONField(default=dict)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('whatsapp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_integration.whatsappuser')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('interactive', 'Interactive'), ('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('content', models.TextField()),
                ('is_incoming', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('whatsapp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_integration.whatsappuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
