# Generated by Django 4.2 on 2025-09-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('whatsapp_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('premium', 'Premium'), ('pro', 'Pro'), ('expired', 'Expired'), ('trial_ended', 'Trial Ended'), ('cancelled', 'Cancelled')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='WhatsAppSubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subscription_created', 'Subscription Created'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_cancelled', 'Subscription Cancelled'), ('subscription_expired', 'Subscription Expired'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_integration.whatsappuser')),
            ],
            options={
                'db_table': 'whatsapp_subscription_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppPaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('pagseguro', 'PagSeguro'), ('mercadopago', 'Mercado Pago')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('pagseguro_transaction_id', models.CharField(blank=True, max_length=255)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=255)),
                ('payment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscriptionplan')),
                ('whatsapp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_integration.whatsappuser')),
            ],
            options={
                'db_table': 'whatsapp_payment_intents',
            },
        ),
    ]
