# Generated by Django 4.2 on 2025-08-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
