# Generated by Django 4.2 on 2025-09-01 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_livematch_matchalert_liveoddssnapshot_livematchevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalyticsPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('auto_generate_reports', models.BooleanField(default=True)),
                ('email_reports', models.BooleanField(default=True)),
                ('whatsapp_reports', models.BooleanField(default=False)),
                ('enabled_widgets', models.JSONField(blank=True, default=list)),
                ('widget_layout', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_competitions', models.ManyToManyField(blank=True, related_name='favorited_by_users', to='core.competition')),
                ('favorite_players', models.ManyToManyField(blank=True, related_name='favorited_by_users', to='core.player')),
                ('favorite_teams', models.ManyToManyField(blank=True, related_name='favorited_by_users', to='core.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics Preference',
                'verbose_name_plural': 'User Analytics Preferences',
                'db_table': 'analytics_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='TeamAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('possession_avg', models.FloatField(blank=True, null=True)),
                ('passing_accuracy', models.FloatField(blank=True, null=True)),
                ('shots_per_match', models.FloatField(blank=True, null=True)),
                ('shots_on_target_ratio', models.FloatField(blank=True, null=True)),
                ('recent_form', models.JSONField(blank=True, default=list)),
                ('home_performance', models.JSONField(blank=True, default=dict)),
                ('away_performance', models.JSONField(blank=True, default=dict)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points_per_match', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.team')),
            ],
            options={
                'db_table': 'analytics_team_analytics',
            },
        ),
        migrations.CreateModel(
            name='PlayerAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('appearances', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('goals_per_90', models.FloatField(blank=True, null=True)),
                ('assists_per_90', models.FloatField(blank=True, null=True)),
                ('pass_completion_rate', models.FloatField(blank=True, null=True)),
                ('expected_goals', models.FloatField(blank=True, null=True)),
                ('expected_assists', models.FloatField(blank=True, null=True)),
                ('progressive_passes', models.IntegerField(blank=True, null=True)),
                ('key_passes', models.IntegerField(blank=True, null=True)),
                ('estimated_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market_value_trend', models.CharField(blank=True, choices=[('rising', 'Rising'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20, null=True)),
                ('recent_performances', models.JSONField(blank=True, default=list)),
                ('consistency_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.player')),
            ],
            options={
                'db_table': 'analytics_player_analytics',
            },
        ),
        migrations.CreateModel(
            name='MatchAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_team_form_score', models.FloatField(blank=True, null=True)),
                ('away_team_form_score', models.FloatField(blank=True, null=True)),
                ('head_to_head_stats', models.JSONField(blank=True, default=dict)),
                ('possession_home', models.FloatField(blank=True, null=True)),
                ('possession_away', models.FloatField(blank=True, null=True)),
                ('shots_home', models.IntegerField(blank=True, null=True)),
                ('shots_away', models.IntegerField(blank=True, null=True)),
                ('shots_on_target_home', models.IntegerField(blank=True, null=True)),
                ('shots_on_target_away', models.IntegerField(blank=True, null=True)),
                ('expected_goals_home', models.FloatField(blank=True, null=True)),
                ('expected_goals_away', models.FloatField(blank=True, null=True)),
                ('passing_accuracy_home', models.FloatField(blank=True, null=True)),
                ('passing_accuracy_away', models.FloatField(blank=True, null=True)),
                ('performance_ratings', models.JSONField(blank=True, default=dict)),
                ('key_moments', models.JSONField(blank=True, default=list)),
                ('tactical_analysis', models.JSONField(blank=True, default=dict)),
                ('predicted_result', models.CharField(blank=True, max_length=50)),
                ('actual_result', models.CharField(blank=True, max_length=50)),
                ('prediction_accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.match')),
            ],
            options={
                'db_table': 'analytics_match_analytics',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('team_analysis', 'Team Analysis'), ('player_analysis', 'Player Analysis'), ('match_prediction', 'Match Prediction'), ('market_analysis', 'Market Analysis'), ('performance_summary', 'Performance Summary'), ('betting_insights', 'Betting Insights')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('content_data', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('widgets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with_users', models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_dashboards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teamanalytics',
            index=models.Index(fields=['team', '-date_from'], name='analytics_t_team_id_751112_idx'),
        ),
        migrations.AddIndex(
            model_name='teamanalytics',
            index=models.Index(fields=['win_rate'], name='analytics_t_win_rat_aa2581_idx'),
        ),
        migrations.AddIndex(
            model_name='teamanalytics',
            index=models.Index(fields=['points_per_match'], name='analytics_t_points__6ba484_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamanalytics',
            unique_together={('team', 'date_from', 'date_to')},
        ),
        migrations.AddIndex(
            model_name='playeranalytics',
            index=models.Index(fields=['player', '-date_from'], name='analytics_p_player__c60dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='playeranalytics',
            index=models.Index(fields=['goals_per_90'], name='analytics_p_goals_p_bbd421_idx'),
        ),
        migrations.AddIndex(
            model_name='playeranalytics',
            index=models.Index(fields=['estimated_market_value'], name='analytics_p_estimat_d4b793_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playeranalytics',
            unique_together={('player', 'date_from', 'date_to')},
        ),
        migrations.AddIndex(
            model_name='matchanalytics',
            index=models.Index(fields=['match'], name='analytics_m_match_i_8c9780_idx'),
        ),
        migrations.AddIndex(
            model_name='matchanalytics',
            index=models.Index(fields=['prediction_accuracy'], name='analytics_m_predict_c0aba4_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['user', '-created_at'], name='analytics_r_user_id_bd0f15_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['report_type', 'status'], name='analytics_r_report__766651_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['date_from', 'date_to'], name='analytics_r_date_fr_5176a7_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['user', 'is_default'], name='analytics_d_user_id_1cb95f_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['is_public'], name='analytics_d_is_publ_aaace9_idx'),
        ),
    ]
